export const products = [
  {
    id: 1,
    name: "iPhone 12 Pro",
    brand: "Apple",
    desc: "6.1-inch display",
    price: 999,
    image: "/images/iphone12pro.jpg",
    details:
      "The iPhone 12 features a 6.1-inch (15 cm) display with Super Retina XDR OLED technology at a resolution of 2532 × 1170 pixels and a pixel density of about 460 ppi. The iPhone 12 Mini features a 5.4-inch (14 cm) display with the same technology at a resolution of 2340 × 1080 pixels and a pixel density of about 476 ppi.",
    color: "Black",
    rating: 5,
    category: "phone",
  },

  {
    id: 2,
    name: "iPhone 12",
    brand: "Apple",
    desc: "5.4-inch mini display",
    price: 699,
    image: "/images/iphone12.jpg",
    details:
      "The iPhone 12 features a 6.1-inch (15 cm) display with Super Retina XDR OLED technology at a resolution of 2532 × 1170 pixels and a pixel density of about 460 ppi. The iPhone 12 Mini features a 5.4-inch (14 cm) display with the same technology at a resolution of 2340 × 1080 pixels and a pixel density of about 476 ppi.",
    color: "Black",
    rating: 0,
    category: "phone",
  },
  {
    id: 3,
    name: "Galaxy S",
    brand: "Samsung",
    desc: "6.5-inch display",
    price: 399,
    image: "/images/galaxyS.png",
    details:
      "The Samsung Galaxy S series is a line of high-end Android smartphones produced by Samsung Electronics. Together with the foldable Galaxy Z series and the now discontinued Galaxy Note series, the lineup serves as Samsung's flagship smartphone lineup.",
    color: "Black",
    rating: 0,
    category: "phone",
  },
  {
    id: 4,
    name: "Redmi Note 12",
    brand: "Xiaomi",
    desc: "6.67-inch display",
    price: 299,
    image: "/images/redmi2.jpg",
    details:
      "The phone comes with a 90 Hz refresh rate 6.43-inch touchscreen display offering a resolution of 1080x2400 pixels at a pixel density of 409 pixels per inch (ppi) and an aspect ratio of 20:9. Redmi Note 11 is powered by an octa-core Qualcomm Snapdragon 680 processor. It comes with 4GB, 6GB of RAM.",
    color: "Black",
    rating: 0,
    category: "phone",
  },
  {
    id: 5,
    name: "Asus Zenphone",
    brand: "Asus",
    desc: "5.9-inch display",
    price: 699,
    image: "/images/zenfone3.jpg",
    details:
      "Asus ZenFone is a series of Android smartphones designed, marketed and produced by Asus. The first-generation ZenFones were announced at the 2014 Consumer Electronic Show in Las Vegas, Nevada. Various models are powered by a series of Intel Atom, Qualcomm Snapdragon, and MediaTek processors.",
    color: "Black",
    rating: 0,
    category: "phone",
  },
  {
    id: 6,
    name: "Acer Predator Triton 500 SE",
    brand: "Acer",
    desc: "16-inch display",
    price: 799,
    image: "/images/acer.png",
    details:
      "Housed in its all-silver chassis, the $2,999.99 configuration of the Triton 500 SE we tested includes a 12th Gen Core i9-12900H processor, RTX 3080 Ti graphics card, 32GB of RAM, and 1TB of PCIe NVME storage. This hardware is more than enough to take full advantage of its 16-inch 240Hz 2560 x 1600 display.",
    color: "Black",
    rating: 0,
    category: "laptop",
  },
  {
    id: 7,
    name: "Asus Zenbook Pro 14",
    brand: "Asus",
    desc: "14.5-inch display",
    price: 1399,
    image: "/images/asus.jpg",
    details:
      "Get ready to meet the seriously powerful Zenbook Pro 14 Duo OLED, an Intel® Evo™-certified powerhouse that lets you turn up your creative powers to the max. The flagship Intel CPU and creator-grade NVIDIA® GPU are cooled for extreme performance by ASUS IceCool Plus technology, aided by the brand-new AAS Ultra mechanism, which vents the chassis and also tilts the next-generation ScreenPad™ Plus secondary touchscreen to a comfortable angle for a seamless and immersive visual experience. ",
    color: "Black",
    rating: 0,
    category: "laptop",
  },
  {
    id: 8,
    name: "OMEN",
    brand: "Hp",
    desc: "17.3-inch display",
    price: 1349,
    image: "/images/hp1.jpg",
    details:
      "A selection of strong hardware components in the HP Omen 17 ensures very strong performance in the processor benchmarks. The 2022 version of the gaming laptop now makes use of an Intel Core i7-12700H from the latest processor generation, which is accompanied by 16 GB DDR5 RAM and a 1 TB NVMe SSD from Western Digital.",
    color: "Shadow black cover and base, shadow black aluminum keyboard frame",
    rating: 0,
    category: "laptop",
  },

  {
    id: 9,
    name: "Asus Vivobook S15",
    brand: "Asus",
    desc: "6.5-inch display",
    price: 2500,
    image: "/images/asus7.png",
    details:
      "Brand new leptop for making your life better. fastest CPU and usable in gaming.",
    color: "Black",
    rating: 0,
    category: "laptop",
  },

  {
    id: 10,
    name: "Acer Nitro 7",
    brand: "Acer",
    desc: "6.5-inch display",
    price: 2000,
    image: "/images/acer2.jpg",
    details: "Acer leptop for gaming. New design and new futures for Acer.",
    color: "Black",
    rating: 0,
    category: "laptop",
  },

  {
    id: 11,
    name: "Redess hat",
    brand: "Redess",
    desc: "gray hat for winter",
    price: 399,
    image: "/images/hat.jpg",
    details: "Brand new hat for winter",
    color: "gray",
    rating: 0,
    category: "clothes",
  },

  {
    id: 12,
    name: "Barts hat",
    brand: "Barts",
    desc: "Hat from BARTS",
    price: 399,
    image: "/images/hat6.jpg",
    details: "Brand new hat for winter",
    color: "Black",
    rating: 0,
    category: "clothes",
  },

  {
    id: 13,
    name: "Adidas",
    brand: "Adidas",
    desc: "Shoe",
    price: 399,
    image: "/images/shoe4.jpg",
    details: "New design adidas.",
    color: "White",
    rating: 0,
    category: "clothes",
  },

  {
    id: 14,
    name: "Boody shirt",
    brand: "Noody",
    desc: "Shirt",
    price: 399,
    image: "/images/Shirt.jpg",
    details: "New Boody shirt for summer.",
    color: "Black",
    rating: 0,
    category: "clothes",
  },

  {
    id: 15,
    name: "Trouser",
    brand: "Nike",
    desc: "Black trouser",
    price: 399,
    image: "/images/trouser.jpg",
    details: "Black trouser for Businessmen. ",
    color: "Black",
    rating: 0,
    category: "clothes",
  },
];
